### PR TITLE
Fix build on x86-64 and empty OUTPUT_DIR

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by RS102839** [comment]
Please withdraw this first fix (to mkspecs), and I can then pull the second fix without needing to cherry-pick it.

**Comment by RS102839** [comment]
It is being checked, but likely that we will accept the request

**Comment by shr-project** [comment]
@RS102839 can we get this merged? please

**Comment by RS102839** [comment]
These three changes all cherry-picked on top of the Qt4.8.3 update.

**Pull request closed without merging**
